---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-sep16-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-sep16-1 
  name: chatbot-sep16-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi